use customer_shopping_db;
select * from customer_shopping;
-- Q1.What is the total revenue generated by the company, the average purchase amount, the minimum purchase amount, and the maximum purchase amount?

select sum(purchase_amount) as total_revenue,avg(purchase_amount) as average_purchase_amount,min(purchase_amount) as minimum_purchase_amount,max(purchase_amount) as maximum_purchase_amount from customer_shopping;

-- Q2.Which product category generates the highest total revenue, and how much revenue does each category generate?

select category,sum(purchase_amount) as total_revenue from customer_shopping
group by category
order by total_revenue desc;

-- Q3.What are the top 10 individual items/products based on total revenue generated?

select item_purchased,sum(purchase_amount) as total_revenue from customer_shopping
group by item_purchased
order by total_revenue desc
limit 10;

-- Q4.Which age group contributes the highest total revenue?

SELECT
    CASE
        WHEN Age < 25 THEN 'Under 25'
        WHEN Age BETWEEN 25 AND 34 THEN '25-34'
        WHEN Age BETWEEN 35 AND 44 THEN '35-44'
        WHEN Age BETWEEN 45 AND 54 THEN '45-54'
        ELSE '55+'
    END AS Age_Group,
    SUM(Purchase_Amount) AS Total_Revenue
FROM customer_shopping
GROUP BY Age_Group
ORDER BY Total_Revenue DESC;

-- Q5.Which 10 locations/states have generated the highest total revenue?

select location,sum(purchase_amount) as total_revenue from customer_shopping
group by location
order by total_revenue desc
limit 10;

-- Q6.Compare total revenue, average purchase amount, and number of customers between male and female customers.

SELECT
    Gender,
    SUM(Purchase_Amount) AS Total_Revenue,
    AVG(Purchase_Amount) AS Average_Purchase_Amount,
    COUNT(*) AS Number_of_Customers
FROM customer_shopping
GROUP BY Gender
ORDER BY Total_Revenue DESC;

-- Q7.Which season generates the highest revenue, and what is the average purchase amount in each season?

select season,sum(purchase_amount) as highest_revenue_season,avg(purchase_amount) as average_purchase_amount from customer_shopping
group by season
order by highest_revenue_season desc;

-- Q8.Do subscribed customers generate more revenue than non-subscribed customers? Compare their total revenue, average purchase amount, and average previous purchases.

select subscription_status,sum(purchase_amount) as total_revenue,avg(purchase_amount) as average_purchase_amount,avg(previous_purchases) as average_previous_purchase from customer_shopping
group by subscription_status
order by total_revenue desc;

-- Q9.Compare customers who received a discount with those who did not. Which group has the higher average purchase amount?

select case when discount_applied="yes" then 'discount_received' else 'no_discount' end as discount_group,avg(purchase_amount) as average_purchase_amount
from customer_shopping group by discount_group
order by average_purchase_amount desc;

-- Q10.How effective are promo codes? Compare customers who used a promo code versus those who did not in terms of total revenue and average purchase amount.

select case when promo_code_used="yes" then "promo_code_applied" else "no_promo_code" end as promo_group,sum(purchase_amount) as total_revenue,avg(purchase_amount) as average_purchase_amount from customer_shopping
group by promo_group
order by total_revenue,average_purchase_amount desc;

-- Q11.Which payment methods are most commonly used, and what is the total revenue generated through each payment method?

select Payment_Method,count(*) AS Number_of_Transactions,SUM(Purchase_Amount) AS Total_Revenue
FROM customer_shopping
GROUP BY Payment_Method
ORDER BY Number_of_Transactions DESC;
select count(item_purchased) as total_count from customer_shopping;

